VRSDevs/XO-Rivals

XO Rivals/Assets/Scripts/Pistolero/CambioEscenaDerrotaVictoria.cs, XO Rivals/Assets/Scripts/Pistolero/CambioEscenaDerrotaVictoria.cs.meta, XO Rivals/Assets/Scripts/Pistolero/ControlBoton.cs, XO Rivals/Assets/Scripts/Pistolero/Cronometro.cs
=> Cambio de tiempo a botón

XO Rivals/Assets/Scenes/TicTacToe_Server.unity, XO Rivals/Assets/Scenes/aasd.unity, XO Rivals/Assets/Scenes/aasd.unity.meta
He creado un menú de instrucciones en un nuevo canvas en la escena TikTakToe_Server.
=> Diseño básico menú instrucciones

XO Rivals/Assets/Scenes/MinijuegoComida.unity, XO Rivals/Assets/Scripts/Comiditas/ComidaController.cs, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/CaminarOKit.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/CaminarOKit.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/IdleOKit.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/IdleOKit.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/MuerteOKit.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/MuerteOKit.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/OKitchen.controller, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/OKitchen.controller.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/VictoriaOKit.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleKitchen/VictoriaOKit.anim.meta
Todas las animaciones de ambos personajes implementadas, falta mejorar el generador,
=> Minijuego comida animaciones implementadas

XO Rivals/Assets/Scenes/Pistolero.unity, XO Rivals/Assets/Scripts/Pistolero/AnimationsController.cs, XO Rivals/Assets/Scripts/Pistolero/AnimationsController.cs.meta, XO Rivals/Assets/Scripts/Pistolero/Cronometro.cs, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/CowboyO.controller, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/CowboyO.controller.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/DisparoCowO.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/DisparoCowO.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/IdleCowO.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/IdleCowO.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/InicioCowO.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/CircleCowboy/InicioCowO.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/CowboyX.controller, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/CowboyX.controller.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/DisparoCowX.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/DisparoCowX.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/IdleCowX.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/IdleCowX.anim.meta, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/InicioCowX.anim, XO Rivals/Assets/Sprites/Minigames sprites/Characters/XCowboy/InicioCowX.anim.meta
Minijuego pistolero con animaciones implementadas. Falta controlar que usuario esta jugando.
=> Animaciones pistolero completadas

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/Créditos/BackButtonCred.cs, XO Rivals/Assets/Scripts/Créditos/BackButtonCred.cs.meta, XO Rivals/Assets/Scripts/Créditos/CambioCreditos.cs
Botón de back en créditos ajustado
=> Soluciono errores basicos

XO Rivals/Assets/Scripts/GameManager.cs, XO Rivals/Assets/Scripts/Network/NetworkCommunications.cs, XO Rivals/Assets/Scripts/Network/NetworkController.cs
Cambio de tipos char a string en el envío de la información en RPCs debido a que no lo reconoce
=> Fix Null System.Char

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs
Pequeña prueba para salir del juego y de la sesión
=> Salir del juego

XO Rivals/Assets/Scenes/MainMenu.unity
Arreglos de algunos errores relacionados con la escena principal (IDs internos y comportamientos de botones)
=> Fix Menú Principal

XO Rivals/Assets/Prefabs/BalaDetect.prefab, XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/BalaDetectScript.cs, XO Rivals/Assets/Scripts/Fantasmas/DetectPlayer.cs, XO Rivals/Assets/Scripts/Fantasmas/EnemyNavMesh.cs, XO Rivals/Assets/Scripts/Fantasmas/LinternaColision.cs, XO Rivals/Assets/Scripts/Fantasmas/LinternaColision.cs.meta
Los enemigos tienen movimiento aleatorio y te persiguen
=> Minijuego fantamas avances

XO Rivals/Assets/Scenes/TicTacToe_Server.unity
Se han implementado los menus de los minijuegos y el lore
=> Instrucciones

XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/DetectPlayer.cs, XO Rivals/Assets/Scripts/Fantasmas/LinternaColision.cs, XO Rivals/Assets/Scripts/Fantasmas/PerderyGanar.cs, XO Rivals/Assets/Scripts/Fantasmas/PerderyGanar.cs.meta, XO Rivals/Assets/Scripts/Pistolero/CambioEscenaDerrotaVictoria.cs
condición de victoria y derrota añadidas a través de unos contadores y colisiones, con esto debería estar acabado el desarrollo, todavía es muy simple la persecución de los enemigos.
=> Fin desarrollo

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/MainMenu/MatchScrollerController.cs
Actualización automática de la lista de partidas para no perder información
=> Actualización automática de la lista de partidas

XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/DesaparecerTiempo.cs, XO Rivals/Assets/Scripts/Fantasmas/DesaparecerTiempo.cs.meta
Implementación de script necesario para ello, un objeto de la maze tendrá este script y se encargará de hacer aparecer y desaparecer algunos muros
=> Muros que desaparecen

XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/MaterialMuro.mat
Lo había actualizado incorrectamente
=> Muros DesaparecenBien

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/MainMenu/SFXManager.cs
Implementacion de metodos para reproducir los sonidos
=> Sonidillos

XO Rivals/Assets/Prefabs/MatchModel.prefab, XO Rivals/Assets/Prefabs/MatchModel.prefab.meta, XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs, XO Rivals/Assets/Scripts/MainMenu/MatchScrollerController.cs
Algoritmo de selección de partida para unirse y respuesta por parte del juego
=> Implementación final de la listas de partidas

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/GameManager.cs, XO Rivals/Assets/Scripts/LoginMenu/Login.cs, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs, XO Rivals/Assets/Scripts/Network/NetworkCommunications.cs, XO Rivals/Assets/Scripts/Network/NetworkController.cs, XO Rivals/Assets/Sprites/UI sprites/ProgressBar_3.png.meta
Arreglo del botón de crear partida (Closes #185 )
=> Reparación BUG de botón de crear partida

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs
Actualización del comportamiento del botón de retroceso para ocultar este fallo
=> Arreglo Sprite del botón Crear Partida

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/Créditos/CambioCreditos.cs
Había un error en el que los créditos no volvian correctamente a su lugar, además la animacion ahora es mas rapida.
=> Soluciono error creditos

XO Rivals/Assets/Scenes/Login.unity, XO Rivals/Assets/Scripts/LoginMenu/Login.cs, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs
Actualización de los triggers del botón de muestra de la contraseña para mostrarla solo cuándo se mantenga pulsado
=> Cambio comportamiento botón para mostrar contraseña

XO Rivals/Assets/Scripts/GameManager.cs, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs, XO Rivals/Assets/Scripts/Network/NetworkController.cs
Implementación correcta del cierre de sesión del jugador
=> Sistema de cierre de sesión

XO Rivals/Assets/Scenes/MinijuegoComida.unity, XO Rivals/Assets/Scripts/Comiditas/ComidaController.cs, XO Rivals/Assets/Scripts/Comiditas/Jugador.cs, XO Rivals/Assets/Scripts/Comiditas/SFXManagerComida.cs, XO Rivals/Assets/Scripts/Comiditas/SFXManagerComida.cs.meta, XO Rivals/Assets/Scripts/MainMenu/SFXManager.cs, XO Rivals/Assets/Scripts/PlatformMinigame/PlayerMovement.cs
Sonidos del minijuego de comida implementados
=> Musica y sonidos

XO Rivals/Assets/Scenes/MainMenu.unity, XO Rivals/Assets/Scripts/LoginMenu/Login.cs, XO Rivals/Assets/Scripts/LoginMenu/PlayFabAuthenticator.cs, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs, XO Rivals/Assets/Scripts/PlayerInfo.cs
Player data (lifes, level) not finished
=> Player Data #1

XO Rivals/Assets/Scripts/MainMenu/MatchScrollerController.cs, XO Rivals/Assets/Scripts/TicTacToe/Match.cs
Eliminación de plantilla y muestra de las partidas activas del jugador
=> Arreglo lista de partidas del jugador

XO Rivals/Assets/Scripts/LoginMenu/Login.cs, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs, XO Rivals/Assets/Scripts/Network/NetworkController.cs
Traducciones de los logs escritos en español a inglés
=> Traducción

XO Rivals/Assets/Scripts/GameManager.cs, XO Rivals/Assets/Scripts/Network/NetworkController.cs, XO Rivals/Assets/Scripts/TicTacToe/TicTacToeController.cs
Pequeño arreglo de la activación del botón al presionar para cancelar la búsqueda
=> Fix comportamiento botón NewGame

XO Rivals/Assets/Scenes/TicTacToe_Server.unity, XO Rivals/Assets/Scripts/Network/NetworkController.cs
Corregido un fallo al salir de la sala
=> Fix botón Join

XO Rivals/Assets/Scripts/MainMenu/MatchScrollerController.cs
Traducción del log en español a inglés
=> Traducciones I

XO Rivals/Assets/Scripts/GameManager.cs, XO Rivals/Assets/Scripts/TicTacToe/ButtonsScript.cs
ahora ya no funcionan los scripts con col y row, funcionan con el gameState.
=> Cambio colRow checkVictory

XO Rivals/Assets/Scenes/TicTacToe_Server.unity, XO Rivals/Assets/Scripts/Network/NetworkCommunications.cs, XO Rivals/Assets/Scripts/TicTacToe/ScreenManager.cs
Cambio a buffered para poder recibir los cambios fuera de la partida
=> Cambio target RPCs

XO Rivals/Assets/Scripts/TicTacToe/ButtonsScript.cs, XO Rivals/Assets/Scripts/TicTacToe/ScreenManager.cs, XO Rivals/ProjectSettings/ProjectSettings.asset
=> Detecta correctamente la victoria

XO Rivals/Assets/Scripts/LoginMenu/Login.cs, XO Rivals/Assets/Scripts/MainMenu/MainMenuController.cs, XO Rivals/Assets/Scripts/Network/NetworkController.cs, XO Rivals/Assets/Scripts/PlayerInfo.cs
Bloqueo de búsqueda de partida al tener 0 vidas y reducción al entrar en la partida
=> Cambio del sistema de vidas

XO Rivals/Assets/Scripts/Network/NetworkCommunications.cs, XO Rivals/Assets/Scripts/TicTacToe/ButtonsScript.cs, XO Rivals/ProjectSettings/ProjectSettings.asset
=> VictoriaDerrotaFuncional

XO Rivals/Assets/Scenes/TicTacToe_Server.unity, XO Rivals/Assets/Scripts/TicTacToe/ButtonsScript.cs
=> SolucionEscenaTurnos

XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/MovePlayer.cs
He solucionado el problema, además de implementar la correcta rotación con teclas y botones.
=> Bug rotacion fantasmas

XO Rivals/Assets/Scripts/TicTacToe/ButtonsScript.cs, XO Rivals/Assets/Scripts/TicTacToe/ScreenManager.cs
Esta implementada usando whosTurn
=> Solución simple bug turno pantalla

XO Rivals/Assets/Scripts/Fantasmas/PerderyGanar.cs
Antes se ganaba cuando los segundos llegaban a 30, ahora cuando llegan a 0.
=> Cambio cuenta progresiva por regresiva

XO Rivals/Assets/Scripts/TicTacToe/ButtonsScript.cs
De esta forma a mi no me da error, es posible que de error a otras personas, en ese caso informar.
=> Bug nombre desaparecido tic tac toe

XO Rivals/Assets/Scripts/MainMenu/MatchScrollerController.cs
Cambio del mensaje de información mostrado al usuario cuando no tiene partidas activas
=> Cambio mensaje de lista vacía

XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/BehaviorTree.meta, XO Rivals/Assets/Scripts/BehaviorTree/Node.cs, XO Rivals/Assets/Scripts/BehaviorTree/Node.cs.meta, XO Rivals/Assets/Scripts/BehaviorTree/Selector.cs, XO Rivals/Assets/Scripts/BehaviorTree/Selector.cs.meta, XO Rivals/Assets/Scripts/BehaviorTree/Sequence.cs, XO Rivals/Assets/Scripts/BehaviorTree/Sequence.cs.meta, XO Rivals/Assets/Scripts/BehaviorTree/Tree.cs, XO Rivals/Assets/Scripts/BehaviorTree/Tree.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckLinterna.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckLinterna.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckNoObstacle.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckNoObstacle.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckRadio.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckRadio.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/EnemyBT.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/EnemyBT.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskPatrol.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskPatrol.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/DetectPlayer.cs, XO Rivals/Assets/Scripts/Fantasmas/EnemyNavMesh.cs, XO Rivals/Assets/Scripts/Fantasmas/LinternaColision.cs
Implementación de la patrulla a través de  arboles de comportamiento.
=> Behaviour Tree Patrulla

XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/BehaviorTree/Tree.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckFollowingPlayer.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckFollowingPlayer.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckGetAdvise.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/CheckGetAdvise.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/EnemyBT.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskAdvise.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskAdvise.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskFollowAdvise.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskFollowAdvise.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskFollowPlayer.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskPatrol.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskWait.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskWait.cs.meta, XO Rivals/Assets/Scripts/Fantasmas/EnemyNavMesh.cs
Implementacion de los fantasmas (todos iguales por el momento) segun este arbol de comportamiento (sin detectar aperturas de puertas).
=> Ghost BT advanced

XO Rivals/Assets/Prefabs/Huella.prefab, XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/EnemyBT.cs, XO Rivals/Assets/Scripts/Fantasmas/DetectHuella.cs, XO Rivals/Assets/Scripts/Fantasmas/DetectHuella.cs.meta
=> Bt ghost advanced2

XO Rivals/Assets/Scenes/Fanstasmas3D.unity
=> Actualizo escena Fantasmas

XO Rivals/Assets/Scenes/PlatformMinigame.unity
El nivel de plataformas se ha ampliado creando nuevas plataformas
=> Ampliacio plataformas

XO Rivals/Assets/Prefabs/Huella.prefab, XO Rivals/Assets/Rendering/UniversalRenderPipelineAsset_Renderer.asset, XO Rivals/Assets/Scenes/Fanstasmas3D.unity, XO Rivals/ProjectSettings/TagManager.asset
=> Cambio iluminacion ghost

XO Rivals/Assets/Scripts/Fantasmas/MovePlayer.cs
no se puede mover diagonal con los botones
=> Elimino movimiento diagonal

XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskAdvise.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskFollowAdvise.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskPatrol.cs, XO Rivals/Assets/Scripts/Fantasmas/BTGhost/TaskPerseguirHuella.cs, XO Rivals/Assets/Sprites/Minigames sprites/Characters/PhantomEnemy/FantasmaListo.controller, XO Rivals/Assets/Sprites/Minigames sprites/Characters/PhantomEnemy/FantasmaMedio.controller, XO Rivals/Assets/Sprites/Minigames sprites/Characters/PhantomEnemy/FantasmaTonto.controller
=> Animaciones ghost

XO Rivals/Assets/Prefabs/Huella.prefab, XO Rivals/Assets/Scenes/Online Scenes/Fanstasmas3D.unity, XO Rivals/Assets/Scripts/Fantasmas/MovePlayer.cs, XO Rivals/Assets/Scripts/Fantasmas/ScriptHuella.cs
Dependiendo de que jugador eres te muestrea un Sprite
=> Cambio respecto a X o O
